FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Set environment variables
ARG VITE_APP_NAME
ARG VITE_APP_BASE_ROUTE
ARG VITE_APP_BASE_URL
ARG VITE_IMAGE_BASE_URL
ARG VITE_API_BASE_URL
ARG VITE_STORE_ID
ARG NODE_ENV
ARG VITE_APP_COPYRIGHT_TEXT
ARG VITE_COUNTRY
ARG VITE_APP_MODE
ARG VITE_PAYMENT_LIVE_CLIENT_ID
ARG VITE_PAYMENT_SANDBOX_CLIENT_ID

ENV VITE_APP_NAME=$VITE_APP_NAME
ENV VITE_APP_BASE_ROUTE=$VITE_APP_BASE_ROUTE
ENV VITE_APP_BASE_URL=$VITE_APP_BASE_URL
ENV VITE_IMAGE_BASE_URL=$VITE_IMAGE_BASE_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_STORE_ID=$VITE_STORE_ID
ENV NODE_ENV=$NODE_ENV
ENV VITE_APP_COPYRIGHT_TEXT=$VITE_APP_COPYRIGHT_TEXT
ENV VITE_COUNTRY=$VITE_COUNTRY
ENV VITE_APP_MODE=$VITE_APP_MODE
ENV VITE_PAYMENT_LIVE_CLIENT_ID=$VITE_PAYMENT_LIVE_CLIENT_ID
ENV VITE_PAYMENT_SANDBOX_CLIENT_ID=$VITE_PAYMENT_SANDBOX_CLIENT_ID

RUN npm run build

# Serve build with custom NGINX config
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

